apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: azure-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: azure-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: azure-cloud-controller-manager
        image: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.<your-minor>.x
        command:
        - /azure-cloud-controller-manager
        - --cloud-provider=azure
        - --cloud-config=/etc/kubernetes/cloud-config/azure.json
        - --leader-elect=true
        - --controllers=*,-cloud-node
        - --v=2
        volumeMounts:
        - name: cloud-config
          mountPath: /etc/kubernetes/cloud-config
          readOnly: true
      volumes:
      - name: cloud-config
        secret:
          secretName: azure-cloud-config
